### ISSUE TITLE
Port ArduinoIoTCloud CI from Travis to Arduino GitHub Actions

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/ArduinoIoTCloud#112]
and add the `size-report` feature for sketch [ArduinoIoTCloud_Travis_CI](examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino).

**Comment by per1234** [comment]
This is currently blocked by https://github.com/arduino/actions/issues/24. I'm starting work on that now.

**Comment by per1234** [comment]
Question: the Travis CI configuration installs the library dependencies by cloning then checking out the latest tag. The reason for doing this instead of using Library Manager is because, between waiting for the indexer job to pick up a new release and for the CDN caches to update the index, it can take a significant amount of time before the release of one of the library dependencies becomes available for installation via Library Manager.

The `arduino/actions/libraries/compile-examples` action currently only allows installing libraries via Library Manager. Will that be a problem?

**Comment by aentinger** [comment]
Good catch :+1: It's not going to be a problem right now but there might be situations (again) where it could be highly annoying. Not always a new library is released although there have been changes to `master`. All in all it would be good if we could also install libraries directly from their github repository but I don't see it as a roadblock right now.

**Comment by per1234** [comment]
Update regarding this:
>the Travis CI configuration installs the library dependencies by cloning then checking out the latest tag. The reason for doing this instead of using Library Manager is because, between waiting for the indexer job to pick up a new release and for the CDN caches to update the index, it can take a significant amount of time before the release of one of the library dependencies becomes available for installation via Library Manager.
>
>The arduino/actions/libraries/compile-examples action currently only allows installing libraries via Library Manager. Will that be a problem?

https://github.com/arduino/actions/pull/48 added support for installing libraries by cloning a repository and checking them out to the latest tag. For example:
```yaml
env:
  UNIVERSAL_LIBRARIES: |
    - source-url: https://github.com/arduino-libraries/Arduino_ConnectionHandler.git
      version: latest
    - source-url: https://github.com/arduino-libraries/Arduino_DebugUtils.git
      version: latest
    - source-url: https://github.com/arduino-libraries/ArduinoMqttClient.git
      version: latest
```

Regarding this:
>Not always a new library is released although there have been changes to master. All in all it would be good if we could also install libraries directly from their github repository but I don't see it as a roadblock right now.

It's also now possible to leave the repository sourced library dependencies checked out to the tip of the default (i.e., `master`) branch if you prefer to test against the development version rather than the release version. For example:
```yaml
env:
  UNIVERSAL_LIBRARIES: |
    - source-url: https://github.com/arduino-libraries/Arduino_ConnectionHandler.git
    - source-url: https://github.com/arduino-libraries/Arduino_DebugUtils.git
    - source-url: https://github.com/arduino-libraries/ArduinoMqttClient.git
```

So if you ever find the current system of installing the library dependencies via Library Manager is inconvenient and want to change this, just let me know and I'll submit a PR.
